### ISSUE TITLE
Cucumber tests for `min-balance`

### ISSUE THREAD

**Issue by tzaffi** [algorand/algorand-sdk-testing#155]
# Introduction

https://github.com/algorand/go-algorand/pull/3287 has introduced `min-balance` to the response of `algod`'s `/v2/accounts/{{ACCOUNT}}` as well as to the `goal account info`.  "For free", it is also introduced into the Python SDK's `account_info()` method. We'll need to implement this functionality in all our other SDK's. To ensure that the SDK's behave as expected, we should adhere to a spec that is defined in a cucumber test.

part of: https://github.com/algorand/indexer/issues/808

# Output

1. Cucumber test that describes what the `min-balance` field should look like when calling `account_info()`
2. Issues for implementing the feature and passing tests in each of the 4 SDK's

**Comment by gmalouf** [comment]
Addressed in #313
