### ISSUE TITLE
`currencyGreaterThan` or `currencyLessThan` should appear in query if the value is explicitly set to 0

### ISSUE THREAD

**Issue by fionnachan** [algorand/algorand-sdk-testing#182]
### Subject of the issue
Various attempts were made to fix https://github.com/algorand/js-algorand-sdk/issues/414 but the PRs were blocked by failed cucumber tests which have an inaccurate expected behaviour for the feature.

See below
|PR author|PR|CircleCI test report|
|-----------|---|---------------------------|
| @algodoggo |https://github.com/algorand/js-algorand-sdk/pull/562|https://app.circleci.com/pipelines/github/algorand/js-algorand-sdk/158/workflows/9878838e-a782-48dc-89c6-0a74df888b9d/jobs/794|
| @barnjamin |https://github.com/algorand/js-algorand-sdk/pull/571|https://app.circleci.com/pipelines/github/algorand/js-algorand-sdk/180/workflows/971cbb96-78b7-4a19-91d2-1b17f4900151/jobs/925|

### Expected behaviour
These are the expected behaviour for the SDK.
1. [working as expected] When `currencyGreaterThan` or `currencyLessThan` is unset, it should not appear in the url query list.
2. [working as expected] When `currencyLessThan` is set to 0, the returned results should be empty or throw an error for disallowed value.
3. [working as expected] When `currencyGreaterThan` is set to 0, the returned result from the API is different from that of when `currencyGreaterThan` is unset. 
    **=> And that's why `currency-greater-than=0` should be in the query list if 0 is set explicitly.** 
4. **[not working]** When `currencyGreaterThan` or `currencyLessThan` is set to 0, it should appear in the url query list.

### Actual behaviour
There are many tests in https://github.com/algorand/algorand-sdk-testing/blob/master/features/unit/v2indexerclient_paths.feature that has the same inaccurate expectation. Below is one of the examples:
`currency-greater-than=0` or `currency-less-than=0` is expected to not appear in the url's query list by the cucumber tests even though `0` is being explicitly set.
![image](https://user-images.githubusercontent.com/13184582/170477678-b8e92467-1ec0-4196-a2e3-16ffa10350f3.png)
https://github.com/algorand/algorand-sdk-testing/blob/d60f7b5c6998ada2b755802a4c53b762063621e4/features/unit/v2indexerclient_paths.feature#L6-L15

**Comment by AlgoDoggo** [comment]
@winder how do you mean? `currency-greater-than=0` works as a query string, it accurately filters out accounts who hold 0 of the asset. It only doesn't work with the algosdk but I use it regularly when consuming the indexer api with other libs.

**Comment by barnjamin** [comment]
This is definitely a bug in at least the JS SDK

This section removes valid zeros
https://github.com/algorand/js-algorand-sdk/blob/18b863be6f4fe435b77c75b62316c0a599d88d68/src/client/client.ts#L25-L33

The work around currently is just to set a string "0" so that it makes it through the checks.

This PR I filed last year was to allow searching valid 0s in the indexer: https://github.com/algorand/indexer/pull/484

**Comment by winder** [comment]
Thanks @barnjamin, I forgot about that! I suppose the testing infrastructure and the SDKs would both need to account for this.

**Comment by fionnachan** [comment]
Those JS PRs have been sitting there for almost 3 months now.... 👀

**Comment by algoanne** [comment]
SDKs need to be able to send 0 for query parameters. There are several transaction endpoints that have this issue/capability. 

To solve this, we need to: 
1. audit our endpoints to make sure we solve it for all affected ones. 
2. update our cucumber tests for each affected endpoint. 
3. update each SDK correspondingly (likely all 4 SDKs, but need to confirm that the behavior appears in the Go and Java SDKs as well). 

we will complete (1) and (2) as part of this ticket, then (3) with individual tickets for each SDK: 
- python: https://github.com/algorand/py-algorand-sdk/issues/296
- JS: https://github.com/algorand/js-algorand-sdk/issues/414
