### ISSUE TITLE
Add the Method object in ABI Results returned from `execute` call of ATC

### ISSUE THREAD

**Issue by barnjamin** [algorand/algorand-sdk-testing#183]
## Problem

I'd like to have access to the method called for a given ABIResult object

## Solution

Add Method to ABIResult object in all SDKs

https://github.com/algorand/py-algorand-sdk/pull/342
https://github.com/algorand/go-algorand-sdk/pull/329
https://github.com/algorand/js-algorand-sdk/pull/578
https://github.com/algorand/java-algorand-sdk/pull/334

**Comment by jasonpaulos** [comment]
Those PRs look good, but I'll add this optional suggestion as well:

We have a cucumber step to check the return value of methods: https://github.com/algorand/algorand-sdk-testing/blob/d60f7b5c6998ada2b755802a4c53b762063621e4/features/integration/abi.feature#L43

Right now each SDK implements this by keeping a separate list of methods that were registered with the atomic transaction composer:
* https://github.com/algorand/java-algorand-sdk/blob/90778d0cb802e57a7b8733cda1555ef89a6ac64c/src/test/java/com/algorand/algosdk/integration/AtomicTxnComposer.java#L142
* https://github.com/algorand/js-algorand-sdk/blob/cd1e9da193388068e0c3096f2bf40af836480d2e/tests/cucumber/steps/steps.js#L5089
* https://github.com/algorand/go-algorand-sdk/blob/300bf87cc7a53805206d078138c2d0093b378ed9/test/applications_integration_test.go#L610
* https://github.com/algorand/py-algorand-sdk/blob/ed3605a3769fcac51eb3328decd62bfb9568e108/test/steps/v2_steps.py#L2911

You could remove these lists and now use the new method field directly on the ABI results value. This would clean up the testing code a little and lend some coverage to the new field.

**Comment by barnjamin** [comment]
Updated the PRs to use the method from the ABI result, waiting for CI

**Comment by barnjamin** [comment]
These PRs have all been merged
