### ISSUE TITLE
SDKs:  Support sourcemap decoding

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/algorand-sdk-testing#198]
## Problem

After adding PC-to-TEAL sourcemaps via https://github.com/algorand/go-algorand/issues/3725, it'd be helpful for SDKs to provide sourcemap decoding capabilities.

Without SDK-provided functionality, users wishing to decode a sourcemap must implement VLQ decoding.  It's a non-trivial exercise and feels like a need that can be met through the SDKs.

## Solution

For Python, @algochoi provided a solution in https://github.com/algochoi/teal-sourcemap-decoder/.

**Comment by barnjamin** [comment]
Python PR https://github.com/algorand/py-algorand-sdk/pull/353

**Comment by barnjamin** [comment]
Go PR https://github.com/algorand/go-algorand-sdk/pull/335

**Comment by barnjamin** [comment]
Testing PR https://github.com/algorand/algorand-sdk-testing/pull/199
