### ISSUE TITLE
SDKs:  Replace logicsig langspec checks with self-contained checks

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/algorand-sdk-testing#213]
## Problem

After each go-algorand AVM release, all SDKs require updated `langspec.json`s + new tests as per https://algorand.atlassian.net/wiki/spaces/SCY/pages/2346844170/Updating+SDK+Langspecs.  To minimize work needed per AVM release, the story requests replacing the existing assertions with equivalents (or near equivalents) that do _not_ rely on a `langspec.json` artifact.

Example existing implementation from py-algorand-sdk:  https://github.com/algorand/py-algorand-sdk/blob/f0509ba40f8ca02c02cc254ea80e5bdbfa2aa9a8/algosdk/logic.py#L45.  Each SDK provides analogous checks.

The replacement checks must confirm the provided program:
* Is _not_ base64 encoded.  Since the input is _bytes_, a common class of mistake is to supply a base64 encoded input. Other plausible mistakes are to send TEAL _source_, or empty bytes.
* Contains TEAL bytecode.  While the new check won't inspect particular opcodes, it feels prudent to confirm the input _resembles_ TEAL.  

As part of the investigation, consider paring down langspec.json to remove _unnecessary_ fields (e.g. budget).  We may ultimately create a separate story, but ought to consider the topic while in the neighborhood.

**Comment by ahangsu** [comment]
The first round investigation result follows:

For Go/JS/Py/Java-SDK: we need to deprecate methods in `Logic`:
- `readProgram`
- `checkProgram`,

deprecate global variables under `Logic`: 
- `spec/langspec`
- `opcodes`
- `logicVersion`
- `evalMaxVersion`.

Related methods using `readProgram`: `LogicsigSignature` constructor and `LogicsigSignature.verify`.
Related methods using `checkProgram`: only in `template`, and `template` is already marked deprecated.

Solution: implement another `sanityCheckProgram` method in `Logic` to substitute `readProgram`, and replace `readProgram` in 2 uses under `LogicsigSignature`.

**Comment by ahangsu** [comment]
Possible deprecation schemes cross SDKs:
- go: mark code as deprecated, applies for both function, struct and variable: https://stackoverflow.com/questions/7849663/how-do-you-mark-code-as-deprecated-in-go
- py: mark function/class as deprecated: use `Deprecation` library: https://stackoverflow.com/questions/2536307/decorators-in-the-python-standard-lib-deprecated-specifically, https://github.com/briancurtin/deprecation
- js: mark code as deprecated, applies for method: https://stackoverflow.com/questions/19412660/how-should-i-mark-a-method-as-obsolete-in-js
- java: mark code as deprecated, applies for methods, class def, class variable: https://stackoverflow.com/questions/9031832/how-to-declare-or-mark-a-java-method-as-deprecated

**Comment by ahangsu** [comment]
Another sub-conclusion from deprecating `langspec.json`: The `readProgram` and `checkProgram` relies on knowledge of opcode `size`, i.e., how many bytes opcode segment totally occupy.

Without such knowledge, one cannot start meaningful test over byte string like disassemble-alike test, other than checking byte code complying to a certain TEAL version. Some other heuristic need to be figured out, without a list of ops with knowledge of size.

**Comment by michaeldiamant** [comment]
For reader ease, here's the associated PRs:
* https://github.com/algorand/algorand-sdk-testing/pull/225
* https://github.com/algorand/go-algorand-sdk/pull/366
* https://github.com/algorand/java-algorand-sdk/pull/367
* https://github.com/algorand/js-algorand-sdk/pull/632
* https://github.com/algorand/py-algorand-sdk/pull/371
