### ISSUE TITLE
Revert `sandbox` branch back to `master`

### ISSUE THREAD

**Issue by algochoi** [algorand/algorand-sdk-testing#259]
We will temporarily point our sdk testing branch to the `last_working` branch in `sandbox`, because the latest commit in `master` does not seem to bring up `indexer` in dev mode.

Specifically, we need to revert this line back: https://github.com/algorand/algorand-sdk-testing/pull/258/files#diff-e9cbb0224c4a3d23a6019ba557e0cd568c1ad5e1582ff1e335fb7d99b7a1055dR25

Link to related issue: https://github.com/algorand/sandbox/issues/161

**Comment by michaeldiamant** [comment]
Closing - Resolved via https://github.com/algorand/sandbox/pull/162 and https://github.com/algorand/indexer/pull/1380.
