### ISSUE TITLE
Inject port and token values into integration tests

### ISSUE THREAD

**Issue by EvanJRichard** [algorand/algorand-sdk-testing#63]
Currently, port and token values are received from the environment, or hardcoded. It would likely be better to define these in the `.feature` files.

Example from indexer testing: 
```
  Background:
    Given indexer client 1 at "localhost" port 59999 with token "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
```

**Comment by ian-algorand** [comment]
Looks like Will did it in the course of doing some other stuff, that champ. Now the tests can choose from multiple clients as appropriate to the test. (ex. so you can test against two different databases at once).
